### ISSUE TITLE
Feature Request: Add a `. .` at the top of each folder as a shortcut for `Up`

### ISSUE THREAD

**Issue by dimven** [derceg/explorerplusplus#138]
Hi,

First of all I have to say explorer++ is incredibly user friendly and seems to be so much more lightweight than the built in win 10 explorer. I've got a few tabs open and it's puling in something like 9 MB of ram, instead of the 30~40MB per each regular excel window. Thanks for the great work!

Secondly, I have a small wish item. It would be great to have the option to add  `..` option at the top of each folder, that will act as the Folder Up / Above shortcut. A lot of the older explorers in windows had this. 7-zip has it too:

![image](https://user-images.githubusercontent.com/7148394/52923804-80133780-3364-11e9-850b-3d8faa26ef0b.png)

and I guess they all in turn inherited it from dos (`cd ..` to go up a folder).

**Comment by cavokz** [comment]
Yes please, '..' is something I'm missing quite a bit.

**Comment by DedicatedTools** [comment]
As a workaround, while in the folder, double-click anywhere in the "white" area.
Personally I find that much easier than aiming at a row such as ".."m at the top (but that's just me)

**Comment by dimven** [comment]
Thanks for the tip. Still it would be great to have the .. in the future for those times when you're predominantly using a keyboard.

**Comment by DedicatedTools** [comment]
For a keyboard workaround, you can use Alt + Up Arrow

**Comment by derceg** [comment]
Given that there are multiple existing ways of doing this (as helpfully pointed out by people above), I'm not sure there's any need for another method. I also think the implementation would potentially be complicated (e.g. should the ".." item be shown in all views, how should its position be affected when sorting, what information should be shown in the details columns, what happens when you right click the item, what happens when you try to drag and drop it, etc). It would likely require a lot of custom handling.
