### ISSUE TITLE
vs2015 compile fail

### ISSUE THREAD

**Issue by poetlj** [derceg/explorerplusplus#141]
hi，when i compile the source code in vs2015,i get many error,just as below,`error	C4579	'nlohmann::detail::static_const<nlohmann::detail::from_json_fn>::value': in-class initialization for type 'const T' is not yet implemented; static member will remain uninitialized at runtime but use in constant-expressions is supported	Explorer++	E:\second\yeestor\explorerplusplus-master\Explorer++\packages\nlohmann.json.3.5.0\build\native\include\nlohmann\json.hpp	309
error	C3520	“I”: The package must be extended in the context parameter
 ( ApiBinding.cpp)	Explorer++	e:\second\yeestor\explorerplusplus-master\explorer++\ThirdParty\Sol\sol.hpp	18764
`and so on,
I have taken a long time to try to fix these errors, pls tell me how to compile the project, many thanks.

**Comment by derceg** [comment]
I don't have the VS2015 toolset installed, so can't easily check whether Explorer++ compiles in it or not. I generally try to support the two most recent versions of Visual Studio, but it becomes difficult to do unless I specifically compile the source in both versions of the compiler every so often.

If the errors are in third party code, there's not a lot I can do about it. Version 3.5.0 is the latest version of the nlohmann/json library. Though if you search their [release notes](https://github.com/nlohmann/json/blob/master/ChangeLog.md) for the error you encountered, it appears that it was fixed in version 3.0.0, but perhaps it was reintroduced.

Both sol2 and nlohmann/json indicate that they're compatible with VS2015, so it sounds like you should be able to compile. Maybe check that you're using the latest version of the compiler.

If it still doesn't work, there's probably not much I can do at this point. Neither sol2 nor nlohmann/json have any new releases that I could try upgrading to. The source definitely compiles in VS2017, so if you can use that, it might be the simplest option right now.

**Comment by poetlj** [comment]
Thank you for your advice,  Explorer++ compiles success in vs2017, my friend tell me that this is a great software, I will try my best to study.Thank you for your efforts！
