### ISSUE TITLE
Can not launch .lnk or .bat file from application toolbar

### ISSUE THREAD

**Issue by sleepyspider1** [derceg/explorerplusplus#145]
This used to work but it no longer works.

**Comment by sleepyspider1** [comment]
It looks like it fails if there's a space in the path. But it's not obvious. Wrapping the path in quotes works around the issue but it's not obvious why it doesn't work.

**Comment by CanuckGamer** [comment]
> It looks like it fails if there's a space in the path. But it's not obvious. Wrapping the path in quotes works around the issue but it's not obvious why it doesn't work.

Paths with spaces needing to be quoted is a Windows standard. Try the same thing in a DOS prompt and you'll get the same result.

**Comment by derceg** [comment]
As mentioned above, paths need to be quoted. Since there's now several things done to make it clearer that paths need to be quoted (an infotip is shown when hovering over the command control, the path will be automatically quoted when selected via the open file dialog and an error message will be shown when opening an item fails), I'll close this issue.
