### ISSUE TITLE
Windows Photos doens't have forwar/back arrows

### ISSUE THREAD

**Issue by jose-guevarra** [derceg/explorerplusplus#167]
Hi,

If I have a bunch of files in a folder and click on an image,  Photos(on windows 10) will have a forward and backward arrows allowing you to progress through all photos in the folder.  This does not happen when viewing with Explorer++.

**Comment by klosworks** [comment]
I can confirm that this is still a problem and an annoying one.
I deal with images a lot and can't use Explorer++ because of this.

It also has been reported on the forum: [https://explorerplusplus.com/forum/viewtopic.php?f=5&t=2038&p=5237&hilit=images#p5237](https://explorerplusplus.com/forum/viewtopic.php?f=5&t=2038&p=5237&hilit=images#p5237)

Explorer++ Version 1.3.5.531 (64-bit Unicode build)

**Comment by klosworks** [comment]
Doesn't work on Version 1.4.0.1211 (64-bit Unicode build) either

**Comment by klosworks** [comment]
Let me just point out that neither GUI arrows nor keyboard arrows work in the Windows 10 Photo Viewer. The image appears as if it was the only image in the folder.

**Comment by klosworks** [comment]
As a workaround I installed the Nomacs Image lounge and set it as my default image viewer. Arrows work in that viewer.

**Comment by derceg** [comment]
Unfortunately, I'm not sure there's much I can do here. I've looked into it in the past and found that while other people have encountered the same problem when opening an image file, I haven't seen any solution raised. I'm not sure what Explorer is doing and there's not really any straightforward way for me to find out.
