### ISSUE TITLE
visual studio version

### ISSUE THREAD

**Issue by hbzhang3** [derceg/explorerplusplus#181]
https://github.com/derceg/explorerplusplus/wiki/Building-Explorerplusplus suggests VS2015/2017, but when i open .sln, it asks for VS2010!

**Comment by hbzhang3** [comment]
am i supposed to build in Debug-LLVM configuration? Anyway after switching to Debug-LLVM it gives "The build tools for ClangCL (Platform Toolset = 'ClangCL') cannot be found" error.

**Comment by derceg** [comment]
The wiki is a bit out of date, but as mentioned above, the solution should compile fine in VS2019. VS2017 should work as well, though I haven't tested it in a while.

As for the Debug-LLVM configuration, it's currently just for testing. Even if you installed the LLVM toolchain, the solution wouldn't compile anyway, due to a few compilation errors.
