### ISSUE TITLE
Suggestion BookmarksToolbar show icon ONLY

### ISSUE THREAD

**Issue by peter8777555** [derceg/explorerplusplus#251]
ApplicationButton can show icon only or show icon with name.

I hope BookmarksToolbar also.
The user can define the special icon for every BookmarksToolbar.

**Comment by derceg** [comment]
My view here is that because the applications toolbar is intended for applications, it's probably ok just to show the icons, since applications tends to have unique icons. The bookmarks toolbar is intended for folders, most of which have the same icon, so showing just the icon wouldn't be as useful.

Although you do have to enter a name when creating a bookmark, you could always just use something like the zero width space character if you don't want anything to be displayed. That way, you could effectively mimic the functionality of the applications toolbar.
