### ISSUE TITLE
My poor English

### ISSUE THREAD

**Issue by peter8777555** [derceg/explorerplusplus#257]
https://explorerplusplus.com/forum/ucp.php?mode=register

I try to register

The question:
What will the next version of Explorer++ be (1.4)?:

My answer :
1.5.0
2.0.0
1.5
2.0
yes

Wrong answer.

Funny.

**Comment by derceg** [comment]
For any anti-spambot question I've added, I think I've always tried to include the answer in parentheses, which is also true in this case. The answer is 1.4, since that's what the next version will be. 1.3.5 is the current stable and 1.4 stable hasn't been released yet.

Ideally, there would no need to have any challenge questions, but each time I've tried to remove them, the forum has been flooded with spam.
