### ISSUE TITLE
[Feature Request] Add ability to associate a shortcut to a bookmark

### ISSUE THREAD

**Issue by blikblum** [derceg/explorerplusplus#292]
This is an specialization of #153

Each bookmark could be associated with a shortcut.

When the shortcut is triggered, the bookmarked folder would be opened in the current tab

**Comment by derceg** [comment]
I've been considering this sort of functionality recently and what I think might be better would be to allow shortcuts to invoke custom actions, using the plugins API. So, rather than adding a shortcut to a bookmark, you could add a shortcut that invokes an action like:

```lua
tabs.create({ location = 'c:\\' })
```

The main advantage would be that shortcuts would have much greater flexibility. You could, for example, have a shortcut that opens three different tabs:

```lua
tabs.create({ location = 'c:\\folder1' }); tabs.create({ location = 'c:\\folder2' }); tabs.create({ location = 'c:\\folder3' });
```

You could then also close tabs or move tabs or take other actions available through the plugins API.

That would potentially have a bit more of a learning curve, but would be a much more powerful system.

It could also be coupled with constraints on when a shortcut is available (similar to the "when" clause available in Visual Studio Code). For example, you could have a shortcut that's available only when the listview has focus, or only when the current tab is in a particular folder. That would also add a lot of flexibility to how shortcuts are handled.

**Comment by derceg** [comment]
This work is now tracked in #476.
