### ISSUE TITLE
regression: opening a folder from command line throws an error

### ISSUE THREAD

**Issue by jlinBE** [derceg/explorerplusplus#337]
running the following command to open the folder "c:":
    
    Explorer++.exe c:
    

Produces the error:
    
    Could not convert: --application-crashed = 11336,9764,0x0,000,00E,FA6,EFB,FB0,893F6631-6D1C-460B-A6B7-D04BB5BA1811
    

This works in 1.3.5, fails silently in 1.40b2, and produces the error above in 1.41.

OS: Windows10 Pro

**Comment by derceg** [comment]
I don't think this crash was because of the command line options. There was a bug fixed last year (see 737f597da0a1ee6df96817481c2c020923703173) related to the "Open new tabs next to the current one" setting in Tools > Options > Tabs. With that option set, the application would crash in situations like the above. Feel free to reopen if this is still happening in the latest build.
