### ISSUE TITLE
Issue #266 still exists in Version 1.4.0 beta 2

### ISSUE THREAD

**Issue by sanxipp** [derceg/explorerplusplus#367]
Explorer++ doesn't work when the folder name with Japanese character is passed on the command line.
ex: folder name: [添付ファイル_E-5]

**Comment by derceg** [comment]
I don't think this has to do with the folder name; rather, the fact that command line paths were previously considered relative to the application directory instead of the current directory. That's something that's recently been [fixed](https://github.com/derceg/explorerplusplus/commit/ea21150210288a05ac40d876de7f69a5136082c9), so if you try this in a newer development build, it should work as expected.
