### ISSUE TITLE
[Bug] Crashes after opening certain folders

### ISSUE THREAD

**Issue by ShinraMyoujin** [derceg/explorerplusplus#368]
I have Windows 10 Pro 21H2 Version, 19044.2130 as build, 64 bits. Release is 1.4.0.1951 dev, 64 bits also.
I have zero information as to why it happens, but I do know a way to fix it (Albeit a little improvised), which is a complete reset via registry. Therefore, I have a feeling it is associated with it, obviously.

The problem, in its entire length, goes as follows: After booting my pc, I opened the AppData (also happens in other folders like Program Files) folder to check certain files, Explorer++ crashed, I tried doing the same in other file managers, and I succeeded. I tried to input directly the file path, it didn't even want to go down the path. I then disabled multiple options that I supposed could interfere, such as “Replace Explorer”, and it still crashed.

At the end, I realized that I had no idea on how to fix it, so I deleted Explorer++, downloaded it again. The issue endured. Consequently, I deleted the Explorer++ registry files, deleted Explorer++ and downloaded it again. Finally, it fixed 'tis concern.

**Comment by derceg** [comment]
I've done some brief tests, but can't reproduce this. Unfortunately, for crashes that appear randomly, there's not much I can do in practical terms.

There's essentially two reasons why the application might crash:

1. A core assumption is broken. For example, it's assumed that there's always at least one tab. If there are no tabs, that's a strong indication of a programming error and the application will deliberately crash, since there's no way to recover.

2. A completely unexpected issue comes up, which causes the application to crash.

I have some planned changes in mind that should make the first type of crash much easier to diagnose. The second type is harder to deal with. There is some basic crash handling in place, but it doesn't always work. To robustly detect crashes, I would probably need to use a third-party library, which would come with its own set of tradeoffs.

To fix any crash, I typically need to be able to reproduce the crash and to do that, I need specific information about when it crashes.

> I tried to input directly the file path, it didn't even want to go down the path.

What sort of path? Did it crash as soon as you entered the text/once you pressed enter/before the list of files were updated/after the list of files were updated?

Did the application crash every time you tried to open a specific folder? What view mode were you using (e.g. medium icons, details, thumbnails, etc)? Does the application crash when using the XML config file?

**Comment by derceg** [comment]
From some further testing, I have seen a crash that I think is likely the cause of the issues here as well. When the "Show folder sizes" option is enabled, the application will crash if a file can't be accessed. From the video you attached, I noticed that you have that option enabled. If you disable that option, do the crashes still occur?

**Comment by laptrinhcomvn** [comment]
It's crashed if I clicked to a downloaded ios screen recorded video.

Link to file debug log:
[https://drive.google.com/file/d/19zz2A6WtTkmUevbtaPdKggDlKUhr02LE/view?usp=sharing](url)

Link to file cause crash:
[https://drive.google.com/file/d/1W6hdDRvgUAs2ffm0hY3pyUSh3uLk3SHQ/view?usp=sharing](url)
