### ISSUE TITLE
Port to MacOS?

### ISSUE THREAD

**Issue by cukabeka** [derceg/explorerplusplus#376]
Hi! 
I hoped this was based on dotnet, which would have raised the chance of a yes for my question, but I'll ask anyhow: 
I'd love to have explorer++ for the mac, as I already loved it during my windows times. I suspect it will be not an easy task, but maybe you can evaluate that Idea better. 
I guess that Electron or QT would be a weird approach , but maybe wxWidgets could work? It is a cross-platform GUI toolkit that allows you to build native desktop apps for multiple platforms, including macOS, using C++.  
Just an idea. :)

**Comment by derceg** [comment]
In the past, I had hoped to gradually write the code in a more platform-independent way, but that hasn't really happened. I think it's actually gone in the other direction, as I've had to add more Windows-specific code to support various features.

There are a few thoughts I have on this overall:

- Using a GUI library would be really nice. I think it would likely make development easier and offer improvements to end users (e.g. Qt has far greater customizability). However, integrating such a library would potentially be difficult and time consuming.

  Back around 2017 or so, I did experiment with Qt a bit. I integrated Qt into the application and recreated the about dialog. Whilst it did work, there were issues with the focus in the dialog not being correctly set. I don't think I ever managed to work out what was going wrong, but it didn't strike me as a good sign to have a problem show up so early.

  Qt is also quite large and I think the setup was more involved.

  I haven't tried wxWidgets, so it might be easier to integrate.

  A key concern for any GUI library is whether it would support the functionality I'm currently using in the Windows common controls. This is perhaps more relevant to something like Qt, since wxWidgets can just wrap native controls, but supporting the current features being used is important.

- Unfortunately, the UI isn't the only consideration. There's a lot of Windows-specific code elsewhere. For example, directory enumeration, directory watching, shell integration (which is used to open Explorer++ when you double-click a folder on the desktop), config loading + saving, along with a lot of other internal code. The architecture of the entire application is basically tied to how Windows does things.

  While some functionality might legitimately be platform-dependent, I think a lot of seemingly core functionality would have to be platform-dependent as well. For instance, Explorer++ is explicitly designed to work with the broader shell namespace. That means it supports virtual folders like This PC and the Recycle Bin. Enumerating those folders is done in a Windows-specific way. I'm not aware of any cross-platform library that abstracts that away, but I can imagine it would be difficult, since shell folders aren't really like filesystem folders.

  For example, shell folders can have several different names, watching a shell folder for changes is done in a different way to watching a filesystem folder, shell folders don't really use string-based paths and the path to a shell folder isn't even necessarily unique (e.g. the virtual desktop folder and filesystem desktop folder both have the same path).

  I'm not sure if there is a cross-platform file manager that supports Windows/Linux/macOS and also supports shell folders on Windows, but if there is such an application, it would be interesting to see what approach they take.

- Given the potential difficulties of updating Explorer++ to run on anything but Windows, one option you could try would be to run it under [Wine](https://www.winehq.org/). I've never done much testing with Wine, but the few times I've run Explorer++ under Wine on Ubuntu, it's at least opened and supported basic browsing. So while I can't say for certain it will work (and I'm sure there's at least some functionality that doesn't work under Wine), it's something you can try immediately, without having to wait for any changes.

Ultimately, it would still be good to use a GUI library, even if porting isn't going to be feasible, so I might look into that again at some point in the future.

**Comment by cukabeka** [comment]
Amazing, thanks for looking into this and sharing your thoughts and expertise. I appreciate this a lot, your insights and the discussion of the options helped me understand better the available possibilities and caveats. 
And I understand that all of this might become quite complex, especially at the filesystem layer. 

I will try to run this in playonmac or crossover, however I'm really looking for a decent system-integrated finder-replacement in the real explorer-Style. I've been searching for this since switching to the mac years ago and the finder still is a PITA. :) 

Thank you, I'll follow what's happening here.
