### ISSUE TITLE
Application terminates immediately after starting

### ISSUE THREAD

**Issue by DustinLuck** [derceg/explorerplusplus#391]
**Describe the bug**
After launching the application, the executable runs, then immediately terminates.

**To Reproduce**
1. Start Task Manager
2. Launch Explorer++
3. See that the Explorer++.exe process is started, then immediately terminates without showing the application window

**Expected behavior**
The application window is shown and remains running until closed.

**Crashes**
[Explorer++1.4.0.1748-12062023-084706.dmp.zip](https://github.com/derceg/explorerplusplus/files/11725777/Explorer%2B%2B1.4.0.1748-12062023-084706.dmp.zip)

**Version (please complete the following information):**
 - Explorer++ version: 1.4.0.1748 (64-bit build)
 - OS: Windows 10 Version 21H2 (OS Build 19044.2965)

**Additional context**
This problem does not happen with Explorer++ 1.3.5 or the latest development build (1.4.0.2192). I'm unsure if this is related to #384 due to the fact that I didn't reproduce it in the same manner.

**Comment by derceg** [comment]
Thanks, it looks like this was fixed in 737f597da0a1ee6df96817481c2c020923703173. The problem was that if the "Open new tabs next to the current one" setting was active, the application could crash on startup.

**Comment by DustinLuck** [comment]
Will you be releasing a new version anytime soon or is there a dev build you consider stable enough for everyday use?

**Comment by derceg** [comment]
I had planned to release 1.4 beta 2 as stable a few years back, but got sidetracked by other things.

Unlike the older nightly builds, where the bookmarks functionality was broken for quite some time, I've tried not to take that approach for a while now in the dev builds. Occasionally small features are disabled or removed, but I try to avoid it. Overall, I try to keep it working reliably.

I have been thinking about just making a release, but I'm not sure there would be too much difference in reliability between a stable version and dev version. There's always going to be issues and my sense is that a stable version would refer more to "unchanging" than "reliable".

The dev versions are where issues, including some long-standing issues, are fixed and new features are introduced, That sometimes means new bugs are introduced, but there's not really a way around that and I try to fix them when I become aware of them. Personally, my recommendation would be to use the dev builds.

Having said that, I might look into fixing the release situation, since I do think it's confusing that there's no recent build tagged as stable,

**Comment by DustinLuck** [comment]
Thanks for a very complete and candid response. I have been using the version from PortableApps.com. I could manually update it with a dev exe, but an official version makes it so much easier 😁. I've reverted to 1.3.5 for now, but I may try a dev build on the side for a while and see how it goes.
