### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by chrisbra** [derceg/explorerplusplus#41]
Hi, thanks for the nice explorer tool. However I have a question. I downloaded the 64bit executable and the german translation. I extracted the german Explorer++DE.dll into the same folder as the Explorer++.exe However, in the options menu the German translation is not visible:
![explorer](https://cloud.githubusercontent.com/assets/244927/10339309/f8c503d0-6d0a-11e5-827e-91db1952d35f.png)

**Comment by chrisbra** [comment]
wow, silently closing after 7 years without any message of an behaviour that  is clearly a bug is quite disappointing!

**Comment by derceg** [comment]
Sorry, I wasn't sure replying at this point would have any impact, but there are a few things:

1. Any issues specific to version 1.3.5 aren't going to be fixed or investigated.
2. I can't reproduce in the latest version and don't think I've encountered this behavior at any other time.
3. Any information from such an old bug likely isn't relevant anymore, given the large number of changes made since then.
4. More generally, there are a number of issues that are years old and keeping them open indefinitely, even when I can't reproduce the reported problems isn't terribly helpful.

If this still reproduces in the latest development build, please file another issue.
