### ISSUE TITLE
Explorer Not Launching in Windows 11

### ISSUE THREAD

**Issue by Alberto-SSanchez** [derceg/explorerplusplus#427]
The program is not being launched/opened in Windows 11, issue happens with both explorers 32/64 bits. I tried launch it as admin but it doesn't work

**To Reproduce**
1. Launch the program, either 32/64 bits

**Expected behavior**
1. Explorer is opened

**Crashes**
[Explorer++1.4.0.2293-30012024-210635.dmp](https://github.com/derceg/explorerplusplus/files/14106728/Explorer%2B%2B1.4.0.2293-30012024-210635.dmp)

**Version**
 - Explorer++ version: Latest https://github.com/derceg/explorerplusplus/releases/tag/version-1.4.0
 ![image](https://github.com/derceg/explorerplusplus/assets/65683678/d930bd53-0959-43a0-8d4c-a899a552e2d7)

 - OS: Windows 11 Home, 22H2

**Comment by derceg** [comment]
Thanks, this was fixed in 737f597da0a1ee6df96817481c2c020923703173. You can either use the dev version, or disable the "Open new tabs next to the current one" setting. Since the application will crash on startup, you can change the setting in the registry/XML file directly. The registry setting is located at HKEY_CURRENT_USER\Software\Explorer++\Settings\NextToCurrent. Set that to 0. If you're using the config.xml file, the setting there is also named NextToCurrent, so it should be easy enough to find.

**Comment by Alberto-SSanchez** [comment]
Thanks for the quick reponse
