### ISSUE TITLE
"Folders always before files" feature dropped (?)

### ISSUE THREAD

**Issue by Tallefer** [derceg/explorerplusplus#71]
In version 1.3.5 folders were always shown before files, no matter the sort order:
![e 135](https://user-images.githubusercontent.com/395476/28026719-9b2cd27c-659f-11e7-834e-501395efff49.png)

Now, in version 1.4.0.99 they are sorted just like files:
![e 140](https://user-images.githubusercontent.com/395476/28026836-e384160c-659f-11e7-83e3-c28444377771.png)

Not sure if this should be a bug report or a feature request, but hey. :)

**Comment by derceg** [comment]
The sorting behaviour has changed since 1.3.5. Files and folders shouldn't be mixed together, but when you change the sort direction, the ordering is simply inverted (which is what happens in Windows Explorer as well). In 1.3.5, folders were always kept on top.

I'm going to close this as the newer behaviour has a simpler implementation and matches that of Explorer.
